test: remove iPhone 13 from test devices
iPhone 13 in Browserstack was failing intermittently with
MediaUnsupportedError: Media Source Extensions not supported

Vinyl does not support browsers without MSE, and while iPhone 13 typically does, the BrowserStack
 environment has been flaky.